pd_app/main/views.py
from flask import render_template, Blueprint


main = Blueprint('main', __name__)


@main.route("/")
@main.route("/home")
def home():
    return render_template('home.html', title='Home')


@main.route("/about")
def about():
    return render_template('about.html', title='About')

pd_app/users/views.py
from datetime import datetime
from sqlalchemy import desc
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from pd_app import db, bcrypt
from pd_app.models import User, Contact
from pd_app.users.forms import RegistrationForm, LoginForm, SearchForm, ContactForm, RequestResetForm, ResetPasswordForm
from pd_app.users.utils import send_reset_email
import pytz



users = Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user_register = User(first_name=form.first_name.data,
                             last_name=form.last_name.data,
                             username=form.username.data,
                             email=form.email.data,
                             password=hashed_password,
                             user_role='member',
                             inserted=datetime.now(pytz.timezone('US/Eastern')))
        db.session.add(user_register)
        db.session.commit()
        flash(f'Your account has been created! You are now able to log in.', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user_login = User.query.filter_by(email=form.email.data).first()
        if user_login and bcrypt.check_password_hash(user_login.password, form.password.data):
            if user_login.user_role == 'member':
                login_user(user_login, remember=form.remember.data)
                next_page = request.args.get('next')
                flash('Signed in!', 'success')
                return redirect(next_page) if next_page else redirect(url_for('users.search'))
            elif user_login.user_role == 'admin':
                login_user(user_login, remember=form.remember.data)
                next_page = request.args.get('next')
                flash('Signed in as Admin!', 'success')
                return redirect(next_page) if next_page else redirect(url_for('users.search'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('login.html', title='Login', form=form)
    

@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)


@users.route("/logout")
def logout():
    logout_user()
    flash('Signed out!', 'success')
    return redirect(url_for('main.home'))


@users.route('/contact', methods=['GET', 'POST'])
def contact():
    form = ContactForm()
    if form.validate_on_submit():
        user_contact = Contact(first_name=form.first_name.data,
                               last_name=form.last_name.data,
                               email=form.email.data,
                               user_request=form.user_request.data,
                               created_date=datetime.now(pytz.timezone('US/Eastern')))
        db.session.add(user_contact)
        db.session.commit()
        flash('Your request have been submitted.', 'success')
        return redirect(url_for('users.contact'))
    else:
        return render_template('contact.html', title="Contact", form=form)

    
@users.route('/search', methods=['GET', 'POST'])
@login_required
def search():
    form = SearchForm()
    return render_template('search.html', title="Search", form=form)


@users.route('/modify', methods=['GET', 'POST'])
@login_required
def modify():
    return render_template('modify.html', title="Resources")

@users.route('/member', methods=['GET', 'POST'])
@login_required
def member():
    members = db.session.query(User).order_by(desc(User.inserted)).all()
    if members:
        return render_template('member.html', title="Members", members=members)
    else:
        msg = 'No Members Found!'
        return render_template('member.html', title="Members", msg=msg)

@users.route('/feedback', methods=['GET', 'POST'])
@login_required
def feedback():
    comments = db.session.query(Contact).order_by(desc(Contact.created_date)).all()
    if comments:
        return render_template('feedback.html', title="Feedback", comments=comments)
    else:
        msg = 'No Members Found!'
        return render_template('feedback.html', title="Feedback", msg=msg)
    return render_template('feedback.html', title="Feedback")    

pd_app/templates/includes/_footer.html
<br>
<footer class="footer">
    <div class="containter">
        <span id="footer-text">On The Web</span>
        <a href="https://www.linkedin.com/in/robyn-carlin-09210010" target="_blank"><i class="fa fa-linkedin-square" style="font-size:24px"></i></a>
        <a href="http://hotsta.org/tag/geauxteach" target="_blank"><i class="fa fa-instagram" style="font-size:24px; color:orange"></i></a>
        <a href="https://twitter.com/geaux_teach" target="_blank"><i class="fa fa-twitter" style="font-size:24px"></i></a>
        <a href="https://www.facebook.com/robyn.carlin.9" target="_blank"><i class="fa fa-facebook" style="font-size:24px"></i></a>
    </div>
</footer>

pd_app/templates/includes/_formhelpers.html
{% macro render_field(field) %}
<b>{{ field.label }}</b>
{{ field(**kwargs)|safe }}
  {% if field.errors %}
    {% for error in field.errors %}
<span class="help-inline"><font color="red">{{ error }}</font></span>
    {% endfor %}
  {% endif %}
{% endmacro %}

pd_app/templates/includes/_messages.html
{% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
        {%  for category, message in messages %}
            <div class="alert alert-{{ category }} alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></span></button>
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
{% endwith %}

pd_app/templates/includes/_navbar.html
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsDefault" aria-controls="navbarsDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarsDefault">
        <ul class="navbar-nav mr-auto">
            <li>
                <a class="nav-link" href="{{ url_for('main.home') }}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li>
                <a class="nav-link" href="{{ url_for('users.contact') }}">Contact <span class="sr-only">(current)</span></a>
            </li>
        </ul>
        <ul class="navbar-nav right">
            {% if session.logged_in and session.role == 'member' %}
                <li>
                    <a class="nav-link" href="{{ url_for('users.search') }}">Search</a>
                </li>
                <li>
                    <a class="nav-link" href="{{ url_for('users.logout') }}">Logout</a>
                </li>
            {% elif session.logged_in and session.role == 'admin' %}
                <li>
                    <a class="nav-link" href="{{ url_for('users.search') }}">Search</a>
                </li>
                <li>
                        <a class="nav-link" href="{{ url_for('users.resource') }}">Resources</a>
                    </li>
                <li>
                    <a class="nav-link" href="{{ url_for('users.member') }}">Member</a>
                </li>
                <li>
                        <a class="nav-link" href="{{ url_for('users.feedback') }}">Feedback</a>
                    </li>
                <li>
                    <a class="nav-link" href="{{ url_for('users.logout') }}">Logout</a>
                </li>
            {% else %}
                <li>
                    <a class="nav-link" href="{{ url_for('users.register') }}">Register</a>
                </li>
                <li>
                    <a class="nav-link" href="{{ url_for('users.login') }}">Login</a>
                </li>
            {% endif %}	
        </ul>
    </div>
</nav>